name: Terraform EC2 + ALB
 
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
 
jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest
 
    env:
      AWS_DEFAULT_REGION: ap-south-1
      TF_ACTION: ${{ github.event.inputs.action }}
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Validate
        run: terraform validate
 
      - name: Terraform Plan
        if: env.TF_ACTION == 'apply'
        run: terraform plan -out=tfplan
 
      - name: Terraform Apply
        if: env.TF_ACTION == 'apply'
        run: terraform apply -auto-approve tfplan
 
      - name: Terraform Destroy
        if: env.TF_ACTION == 'destroy'
        run: terraform destroy -auto-approve